# Generated by Django 3.2.16 on 2024-03-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Confirmation code'),
        ),
        migrations.AddField(
            model_name='user',
            name='confirmation_code_expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время истечения кода подтверждения'),
        ),
    ]
