# Generated by Django 3.2.16 on 2024-03-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240328_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='tries',
        ),
        migrations.AddField(
            model_name='user',
            name='otp_tries',
            field=models.IntegerField(default=0, verbose_name='Attempts to verificate or log in'),
        ),
    ]
